### ISSUE TITLE
test again with a few texts from the full corpus

### ISSUE THREAD

**Issue by JonathanReeve** [Git-Lit/git-lit#13]
The full corpus just arrived from the British Library! The directory structure and file naming conventions are a little different, though, so it'll require some reworking.

**Comment by tfmorris** [comment]
Cool!  Perhaps you could post a directory listing somewhere so we can see what we have to work with...

**Comment by JonathanReeve** [comment]
I thought I did but it turns out it was a blank file! Thanks for catching that. Uploaded at https://raw.githubusercontent.com/Git-Lit/git-lit/master/full-corpus-filenames-list.txt.

**Comment by JonathanReeve** [comment]
Oh and I just posted a few more sample files from the full corpus in `data2`.

**Comment by JonathanReeve** [comment]
I also just uploaded all the metadata files from all the texts, in metadata/metadata-files. 

New code is working with the new data structure. Closing this.
