### ISSUE TITLE
text repositories should contain titles

### ISSUE THREAD

**Issue by JonathanReeve** [Git-Lit/git-lit#2]
Right now, I'm only using text IDs as repository names, but it'd be better to use text titles and IDs. To do this, I need to sanitize titles in a slightly different way than GITenberg is, because there are more strange characters in BL documents.

**Comment by sethwoodworth** [comment]
A huge rationale for abandoning github is their lack of support for unicode repository titles. Github has a hard limit on 100 characters, and changes unicode characters to `-`.  I have several repositories that are a long string of `-`s with the Gutenberg ID at the end.

**Comment by JonathanReeve** [comment]
Thanks, Seth! Good to know. I'm thinking it will be nice (and compatible-ish with GITenberg) to do text repositories in your style, like `Moby-Dick-25235`. The sanitizing functions in `gitberg` weren't working for the BL texts, though, so I might have to write something a little different for it. I'm thinking: 
- [x] grab the title from the metadata
- [x] convert spaces to hyphens
- [x] ASCII-ize non-ASCII characters (convert `é` to `e`, for example)
- [x] shorten the title so that it can fit along with the ID and stay under 100 characters

**Comment by prpole** [comment]
Made a pull request with the easy parts, i.e. 1 2 and 4. Three will be more complicated.

**Comment by JonathanReeve** [comment]
Awesome, thanks! Merged.

**Comment by JonathanReeve** [comment]
Titles are looking good now! Closing.
