### ISSUE TITLE
Delete data directory and move data2 to data

### ISSUE THREAD

**Issue by tfmorris** [Git-Lit/git-lit#20]
Am I correct in assuming that the original `data` subdirectory is obsolete and the `data2` directory matches (or is closer to) the format of the data from the BL?

I'm happy to do the work, just want to make sure I'm understanding things correctly.

**Comment by tfmorris** [comment]
@JonathanReeve Are you OK with me making this change?

**Comment by JonathanReeve** [comment]
Absolutely. Go for it. Good idea.
