### ISSUE TITLE
Add a multi-volume example

### ISSUE THREAD

**Issue by tfmorris** [Git-Lit/git-lit#22]
It looks like one of the samples is the first volume of a multi-volume set.  It would be useful to have the other volume too.

The zip filename should be `000000216_2_1-286pgs__638718_dat.zip`.  Volume 1 is `000000216_1_1-318pgs__632698_dat.zip`

**Comment by JonathanReeve** [comment]
True. I'll add a sample from the corpus on Friday.

**Comment by tfmorris** [comment]
Thanks!

For the future, we only need the zip files.  The current code extracts both metadata and ALTO files directly from the .zip without having to explode them first.

Unless you've got a strong objection, I'm going to delete all the extra stuff to keep things streamlined.  Developers are, of course, free to unzip the files locally if needed (I do this for debugging).

**Comment by tfmorris** [comment]
Oops, I should have checked more closely.  The zip files are missing, so these can't be used at all with the current code.  Also, I thought we agreed that we were going to switch from `data2` to `data` and these ended up in `data2`.

I'd suggest either:
1. All zip files directly in a single directory (ie `data`)
2. A subdirectory for each book containing the zip files for all volumes (mostly it'll just be a single)

Case 2 is closest to what we have now and would result in a hierarchy like:

```
data
    000000216
        000000216_1_1-318pgs__632698_dat.zip
        000000216_2_1-286pgs__638718_dat.zip
```

**Comment by JonathanReeve** [comment]
I see the zip file stuff now. That's awesome. Solves a lot of problems. The BL originally gave me only zip files, and I just expanded them with a bash script, so it'd be great if I could cut out that step. 

All zip files in one directory would be the easiest way to go. If we don't need anything in `data`, I'll just remove everything there and add new sample zip files.

**Comment by JonathanReeve** [comment]
Oops, didn't mean to close.

**Comment by JonathanReeve** [comment]
Ok, I think it should be good now. All zip files in the data dir. If we can figure out ways to parse these zip files, that'd be great, and would save a few steps, since all the original files are all zip files in this format. Multi-volume stuff should be a little tricky.

**Comment by tfmorris** [comment]
Excellent, thank you! By my count we now have 10 sample volumes, including a 2 volume edition and a 3 volume edition.

An associated change that I'll make over the weekend is to make the corpus builder take a file list (probably in a file), so that you aren't required to scan everything in a single directory.
