### ISSUE TITLE
make a project github.io page

### ISSUE THREAD

**Issue by JonathanReeve** [Git-Lit/git-lit#3]
This project needs a website to advertise it.

**Comment by tfmorris** [comment]
I've created the necessary repo and generated a placeholder web site:
http://git-lit.github.io/

The repo is https://github.com/Git-Lit/Git-Lit.github.io (which we might be able to lowercase to git-lit since that's what the URL ends up as).

**Comment by JonathanReeve** [comment]
Great! Thanks for doing that. I'll import the README.md for now, but feel free to edit at will!

**Comment by JonathanReeve** [comment]
Imported readme. I'll close this for now, and open a new one for expanding and rewriting the website.
