### ISSUE TITLE
Switch to Python 3?

### ISSUE THREAD

**Issue by JonathanReeve** [Git-Lit/git-lit#35]
I don't want to throw people off of their workflows, but since we're likely to deal a lot with unicode here, python 3 might be the way to go. I'll try to convert existing code with `2to3`, and hopefully it should still work with python 2.

**Comment by JonathanReeve** [comment]
Fixed in c1515eaa87966bcb93e71414f22e51e675d9efdf.

**Comment by sethwoodworth** [comment]
I've been holding off doing much directly with the texts in gitenberg until
I can get everything tested in py3. I think it is worth doing.

**Comment by tfmorris** [comment]
I'd like to see both 2.7 and 3.x supported until such time as we find
something that can't be done in 2.7 and are forced to drop support for it.

The `from __future__ import xxx` facility does a pretty good job of
allowing common code to be used for both Python 3.x and later 2.x versions
(2.6+?).
