### ISSUE TITLE
Add titles to repo names

### ISSUE THREAD

**Issue by JonathanReeve** [Git-Lit/git-lit#43]
Currently, repo names are only the book IDs, but it'd be nice to have to titles, too, in the style of Gitenberg, such that The Adventures of Huckleberry Finn, with ID 2359827 has a repo name of `adventures-of-huckleberry-finn-2359827`.

**Comment by tfmorris** [comment]
That's an improvement for the simple case, but can lead to ugly repo names if you're not careful, viz 
https://github.com/gitenberg-dev/gitberg/issues/77
https://github.com/GITenberg/------------------------------------------------------------13--------------------------_31434

Gitenberg doesn't have it right yet, so I wouldn't suggest following them. Some of the suggestions I made to them:
- diacritic folding
- eliding illegal (to Github) characters before they get sent so they don't get turned into hyphens
- using fallback titles if they're present and the main title has few enough legal characters (threshold TBD)
- transliteration if all else fails

**Comment by eshellman** [comment]
we did the first two things on Tom's list six weeks ago, as it was just a few lines of python. 
https://github.com/gitenberg-dev/gitberg/blob/master/gitenberg/book.py#L107

**Comment by JonathanReeve** [comment]
Since this seems like it'll cause problems, I'll just go with numeric IDs only, for now.
