### ISSUE TITLE
ASCIIDOC encoding errors

### ISSUE THREAD

**Issue by JonathanReeve** [Git-Lit/git-lit#46]
This may be something already in the ALTO, but some of the ASCIIDOC files contain lots of `â€”` characters in place of curly quotes. Maybe this is an encoding issue?

**Comment by tfmorris** [comment]
Pointer (doc & page)? Is this in the output as rendered by Github, rendered by another tool, or in the raw source file? If the source, viewed with what tool and on what operating system?

**Comment by JonathanReeve** [comment]
Haven't seen this recently. Maybe it was just a problem on my end. Closing.
