### ISSUE TITLE
transform ALTO XML into ASCIIDOC

### ISSUE THREAD

**Issue by JonathanReeve** [Git-Lit/git-lit#5]
Similar to what GITenberg is doing.

**Comment by tfmorris** [comment]
Have you got a pointer for this?  I didn't think GITenberg was doing anything like ABBYY/ALTO XML to ASCIIDOC.

**Comment by eshellman** [comment]
GITenberg has not done much \* --> asciidoc work; it's the asciidoc --> htmlbook --> epub chain that we've worked on.

**Comment by sethwoodworth** [comment]
At most we have run `pandoc` on Gutenberg HTML files. I suspect something
new will need to be written for ALTO > asciidoc.

**Comment by JonathanReeve** [comment]
It looks like @tfmorris has made some great progress with this. I'll close this one, and we can open a more specific issue for the nuances of the ALTO -> ASCIIDOC chain.
