### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by JonathanReeve** [Git-Lit/git-lit#51]
This will just make things so much easier. We can remove all the `from __future__ import` statements, and we won't have to worry about wrapping strings in unicode flags. This work is mostly finished in the `python3` branch, but I'm just leaving this issue here as a placeholder until it merges into master.

**Comment by tfmorris** [comment]
Why would you remove the `from __future__` imports? Aren't they noops in Python 3?

**Comment by JonathanReeve** [comment]
I thought stuff like `from __future__ import division` was just a way to be able to use nice floating-point division from Python 3 in Python 2. Is there a future from the Python 3 standpoint? I admit I don't know very much about this.

**Comment by JonathanReeve** [comment]
I finished porting this to Python 3, so this should fix it. Closing.

**Comment by tfmorris** [comment]
> I thought stuff like from **future** import division was just a way to be
> able to use nice floating-point division from Python 3 in Python 2. Is
> there a future from the Python 3 standpoint? I admit I don't know very much
> about this.
> 
> Anything done using `__future__` imports should work the same on both
> Python 2 and Python 3. I was just questioning the value in doing extra work
> to drop Python 2 when the lowest effort path was to support both -- but too
> late now.
