### ISSUE TITLE
what text format(s) should we use? 

### ISSUE THREAD

**Issue by JonathanReeve** [Git-Lit/git-lit#6]

**Comment by sethwoodworth** [comment]
We use asciidoc (via asciidoctor), but there is little reason why that need be the case here.  I don't 100% understand what is available in ALTO xml, but if you can associate a word with a page, that is very useful information to retain as a text coordinate in citations and for deep linking.

Ultimately, there are at least two goals for these books to address:
- Producing modern epubs for consumption
- Providing canonical citation sources

The first goal suggests making edits to modernize a text.  The second suggests we should preserve data at the possible cost of usability.  Ideally, we could serve both equally well.

**Comment by tfmorris** [comment]
I wouldn't put epubs, particularly those which have been "modernized," as a primary goal.  In my mind, crowdsourced corrections of OCR should be one of the main goals and there is no tension between popular and scholarly needs there (except in the minds of academics who trust their own personal slaves, errr grad students, more than the unwashed masses).

The goal that I would add is ease of contribution.  Lowest common denominator formats enjoy wider tool support, but also carry much less information.  Formats like ALTO are very rich, but completely unknown outside archivist niches.

As far as ALTO information goes, interestingly, the ALTO folks live on Github now too: https://github.com/altoxml and their home page at the Library of Congress is: http://www.loc.gov/standards/alto/

As used in the British Library corpus, assuming it's consistent with the small sample that I looked at, the hierarchy is page, text block, line, word, with each word having a unique ID, X & Y coordinates, width, OCR confidence (0-1.00), and a list of OCR character confidences (0-9). looks like the snippet below.  This mass of XML encodes the text "for themselves. The woman also found a needle and" 

``` xml
<alto>
    <Description>
           [information about source image, preprocessing and OCR software]
    </Description>
    <Styles>
                [list of text and paragraph styles for this file, e.g.]
        <TextStyle ID="TXT_0" FONTSIZE="11" FONTFAMILY="Fraktur"/>
        <TextStyle ID="TXT_1" FONTSIZE="9" FONTFAMILY="Courier New"/>
        <ParagraphStyle ID="PAR_LEFT" ALIGN="Left"/>
    </Styles>
    <Layout>
        <Page ID="P20" PHYSICAL_IMG_NR="20" HEIGHT="1935" WIDTH="1116" PRINTED_IMG_NR="22" POSITION="Left" ACCURACY="69.69">
            <TopMargin ID="P20_TM00001" HPOS="0" VPOS="0" WIDTH="1115" HEIGHT="66">
                <TextBlock ID="P20_TB00002" HPOS="276" VPOS="44" WIDTH="617" HEIGHT="21" STYLEREFS="TXT_1 PAR_RIGHT">
                    <TextLine ID="P20_TL00002" HPOS="277" VPOS="44" WIDTH="616" 
                                        [Header text]
                    </TextLine>
                </TextBlock>
            </TopMargin>
            <LeftMargin ID="P20_LM00001" HPOS="0" VPOS="66" WIDTH="126" HEIGHT="1779">
                               [text blocks containing left margin text (noise in this case)]
            </LeftMargin>
            <RightMargin ID="P20_RM00001" HPOS="1050" VPOS="66" WIDTH="65" HEIGHT="1779"/>
            <BottomMargin ID="P20_BM00001" HPOS="0" VPOS="1845" WIDTH="1115" HEIGHT="89"/>
            <PrintSpace ID="P20_PS00001" HPOS="126" VPOS="66" WIDTH="924" HEIGHT="1779">
                <TextBlock ID="P20_TB00005" HPOS="126" VPOS="130" WIDTH="919" HEIGHT="838" STYLEREFS="TXT_1 PAR_LEFT">
                    <TextLine ID="P20_TL00005" HPOS="128" VPOS="132" WIDTH="917" HEIGHT="31">
                        <String ID="P20_ST00011" HPOS="128" VPOS="135" WIDTH="43" HEIGHT="28" CONTENT="for" WC="0.76" CC="007"/>
                        <SP ID="P20_SP00007" HPOS="171" VPOS="163" WIDTH="16"/>
                        <String ID="P20_ST00012" HPOS="187" VPOS="134" WIDTH="185" HEIGHT="29" CONTENT="themselves." WC="0.88" CC="05000004020"/>
                        <SP ID="P20_SP00008" HPOS="372" VPOS="163" WIDTH="46"/>
                        <String ID="P20_ST00013" HPOS="418" VPOS="133" WIDTH="59" HEIGHT="29" CONTENT="The" WC="0.99" CC="000"/>
                        <SP ID="P20_SP00009" HPOS="477" VPOS="163" WIDTH="17"/>
                        <String ID="P20_ST00014" HPOS="494" VPOS="143" WIDTH="113" HEIGHT="19" CONTENT="woman" WC="0.90" CC="00003"/>
                        <SP ID="P20_SP00010" HPOS="607" VPOS="163" WIDTH="22"/>
                        <String ID="P20_ST00015" HPOS="629" VPOS="133" WIDTH="60" HEIGHT="28" CONTENT="also" WC="1.00" CC="0000"/>
                        <SP ID="P20_SP00011" HPOS="689" VPOS="163" WIDTH="17"/>
                        <String ID="P20_ST00016" HPOS="706" VPOS="132" WIDTH="90" HEIGHT="29" CONTENT="found" WC="0.64" CC="04660"/>
                        <SP ID="P20_SP00012" HPOS="796" VPOS="163" WIDTH="23"/>
                        <String ID="P20_ST00017" HPOS="819" VPOS="142" WIDTH="18" HEIGHT="18" CONTENT="a" WC="0.17" CC="8"/>
                        <SP ID="P20_SP00013" HPOS="837" VPOS="163" WIDTH="22"/>
                        <String ID="P20_ST00018" HPOS="859" VPOS="132" WIDTH="106" HEIGHT="28" CONTENT="needle" WC="0.82" CC="700200"/>
                        <SP ID="P20_SP00014" HPOS="965" VPOS="163" WIDTH="23"/>
                        <String ID="P20_ST00019" HPOS="988" VPOS="132" WIDTH="57" HEIGHT="28" CONTENT="and" WC="0.51" CC="077"/>
                    </TextLine>
```

**Comment by quinncomendant** [comment]
For greatest adoption and interchangeability, I would suggest markdown. See perspective given in [Sustainable Authorship in Plain Text using Pandoc and Markdown](http://programminghistorian.org/lessons/sustainable-authorship-in-plain-text-using-pandoc-and-markdown).

**Comment by sethwoodworth** [comment]
GITenberg avoided markdown due to a lack of a standard.  Markdown's support for formatting like footnotes, reference blocks (poetry, songs), and even images are inconsistent across implementations and not covered in a specification anywhere.  Asciidoc is very similar in formatting marks, but has a specification.

Ultimately, I think the lack of a WYSIWYG editor is a higher barrier to entry.  [Gitbook](gitbook.com) is a great interface for asciidoc and markdown, and is _mainly_ open source.

**Comment by JonathanReeve** [comment]
Glad to see you here, @quinncomendant! Although I'm a rabid fan of markdown myself, and use it for about all my projects and writing, I'm definitely enticed by the richness of ASCIIDOC's features and toolset. Also, while Pandoc markdown is fairly feature-rich, there are some differences between it and GitHub-flavored markdown, which is what I imagine amateur editors might use to edit books in the browser. 

Thanks for reminding me about Gitbook, Seth--I hadn't imagined it as part of the toolchain here, but that's a really forward-thinking idea. I think it'd be wise to imagine creating modern ebooks down the road, and so it'd be good to think about these sorts of things now. We could also keep the ALTO, but just encourage editing on the ASCIIDOC versions of texts.  

@denten and @gwijthoff, I'd be interested to hear your thoughts on this, since your article is cited above.

**Comment by denten** [comment]
[Common Mark](http://commonmark.org/) is the way to go. It is supported by MacFarlane (Pandoc), Jeff Atwood (Stack Exchange, Coding Horror) and others from GitHub and Reddit. It provides:

> a standard, unambiguous syntax specification for Markdown, along with a suite of comprehensive tests to validate Markdown implementations against this specification. 

Add YAML and you have a pretty robust stack. That's what we've been using for most of the projects in our lab.

**Comment by quinncomendant** [comment]
Hey Jonathan! Thanks for the tips to asciidoc and commonmark — both very encouraging. 

What is the anticipated skill level of git-lit contributors? It's worth considering the environment and workflow that readers/editors will use. E.g., if book editing is to be done in a markdownish format, that posits the editor will be reading the book in their markdown editor (which might take some persuasion). What if user reads books in an epub reader app on a tablet in which highlighting and notes could be applied to text that needs correction; wouldn't it be nice if the epub reader could export a diff file? Does iOS/Android book reading app exist that is also a git client?

One criteria of selecting a text format is ease of adoption, but also of concern is adopting a _reading_ format/environment. If reading/editing is done in a wysiwyg environment, and output formats are controlled by a conversion pipeline (pandoc or asciidoc) then the text format is an intermediary format, and the only criteria is its support by the tools at either end of this pipeline.

**Comment by denten** [comment]
Heya @quinncomendant. Markdown would require only a plain text editor like Vim, Emacs, Sublime, Atom, Leafpad, Notepad++, etc... The whole point is not to get locked into any specific platform. @JonathanReeve will correct me if I am mistaken, but the idea here is to use github as a community edited backed that provides APIs, version control, diffs, etc... It would be up to others to build reading platforms on top of the archive and up to the reader to select their favorite reading environment. The backend remains platform agnostic as much as possible.

**Comment by quinncomendant** [comment]
I just noticed there are plenty of git client/text editors available for iOS, which will really be a boon for the hammock-bound editors.

@sethwoodworth mentioned a wysiwyg editor above, so I thought that might be a requirement. Indeed, just define the APIs and let people interface with it how they like.

**Comment by sethwoodworth** [comment]
An ebook reader app that can report issues or submit changes would be amazing.  There has been some offline discussion about it around GITenberg, but it's been too ambitious for us to take on yet.  A dedicated editor that connects with Git-Lit and GITenberg should be easier to implement first.  Gitbook's editor supports markdown (with their own extensions) and asciidoc.  I would love to collaborate on an editing platform.

**Comment by eshellman** [comment]
Decoupling the choice of text format from machinery, where possible, is also important. So that's a good argument for doing metadata outside the text format (as we've done in GITenberg). Repo layout should not be tied to text format. (Gitbook has some good ideas on that.) The mathematicians are not going to leave LaTeX; TEI is good for what it does, and HTML is not dead. Many of the Distributed Proofreaders are going to be won over by good implementations of drop caps and ornamental breaks.

**Comment by tfmorris** [comment]
OK, time to pick one, at least to start.  #5 implies asciidoc is the choice, but this issue was created later.

Both asciidoc and Markdown are supported by Github with in-place rendering on their web site.

I've implemented a simple ALTO->asciidoc translation which would be easy enough to retarget to Markdown, but the more work we do, the harder it'll be to switch, particularly once we start creating large numbers of repos.

**Comment by tfmorris** [comment]
Ping! Do we have a winner yet? Do we need to do more investigation? Have we got a set of decision criteria at least?

**Comment by JonathanReeve** [comment]
I like the idea of going with ASCIIDOC for the future. It's feature richness, disambiguity, and toolchain are all attractive to this task. But the idea of automatically generating websites for each book is too good, and it seems like that's only possible with Markdown (Kramdown-flavored), since we're only allowed to use vanilla Jekyll on GitHub Pages. I'd say let's go with markdown for now, and then bookmark ASCIIDOC for the future.

**Comment by tfmorris** [comment]
There will be a significant investment in whatever format is chosen in the form of converter software, style guides, user training, etc. The user training issue (& style guide) can be mitigated by not exposing the markup language for direct user editing, but then you need some sort of supporting editor or front end tooling. If a community of volunteers is going to be directly editing the markup language, I think a 3-5 year lifetime is the _minimum_ horizon that should be contemplated when making the decision.

It might be useful to make a (prioritized?) list of decision criteria. It'd be easy to set up something like Travis CI to regenerate static web pages for hosting on Github Pages (or elsewhere), so automatic website generation wouldn't be at the top of my list (although I **do** find the online preview that Github supports useful for casual editing, but that's supported for .adoc as well as .md). Note that Jekyll extensions, like jekyll-scholar will require external generation even for Markdown/kramdown.

p.s. Although the issue is couched in terms of the markup language, it's really about the entire supporting toolchain, so should be considered in that context.

**Comment by denten** [comment]
I strongly agree with @tfmorris. We have had a similar discussion at the Small Axe project (where we are are creating a hybrid online / print edition using free and open source toolchain). After a lengthy discussion, we decided to go with Pandoc markdown. Pandoc is an academic community responsive to our needs in the long term (active mailing list, maintainers respond immediately to issues). The tool is extensible through filters. It is well documented. Plugins exist to address the Pandoc > Kramdown conversion if needed. 

Remember also that Markdown is a format meant to be readable at the source. This in fact is its subversive strength: it gets people away from complex formatting. With this mindset, citation and annotation should happen with reference to the source. This means hard line breaks and little crud. Markdown is a virus for plain text. I am interested in the vision of Git Lit as a project that is concerned with clean, minimally marked up **sources** not with presentation.

Re: lack of standards @sethwoodworth. It is a feature. See https://tools.ietf.org/html/rfc7763:

> [MDSYNTAX] explicitly rejects the notion of validity:
>    there is no such thing as "invalid" Markdown.  If the Markdown
>    content does not result in the "right" output (defined as output that
>    the author wants, not output that adheres to some dictated system of
>    rules), the expectation is that the author should continue
>    experimenting by changing the content or the processor to achieve the
>    desired output.

**Comment by rufuspollock** [comment]
I am flagging Textus format - http://okfnlabs.org/textus/doc/textus-format.html - this has a separation between raw text stream (either plain ascii, or, possibly something like markdown) and separate markup as JSON. JSON markup largely builds on existing standards and allows for e.g. TEI as well as HTML and full annotations.

A note on stuff like markdown: it always seems great to begin with but you rapidly run into issues with more complex demands e.g. wanting to record richer structure such as chapters etc. Textus allows for "gradual" enhancement - start with plain text (or markdown) and add structure in separate files.

**Comment by denten** [comment]
This is where @tfmorris's suggestion becomes important. The git-lit project needs a scope statement. For example, I am interested in a "human-readable, minimally marked up, version controlled, extensible" corpus of texts. Others may be closer to the TEI vision of "maximally encoded, machine-readable standards," yet others in "source code for beautiful typesetting." There are no wrong answers, but to get the right one I suggest drafting a short "design spec" of prioritized criteria @JonathanReeve.

**Comment by rufuspollock** [comment]
I'm a big +1 on markdown or plain ascii for the basic texts -- that's what Textus stuff was designed around. If you end up with complex formatting in the raw text you basically have a high barrier to entry for users. The "sidecar" metadata approach of Textus means you can add extra formatting etc when you need it.

Personally I'd be a +1 on basic markdown because of the breadth of tooling and integrated support in github (it was the approach taken back in the day with the open shakespeare stuff and it was what inspired the Textus approach).

**Comment by JonathanReeve** [comment]
I'll try to summarize the main points from this thread, so that we can make a decision and move on. There seem to be a lots of advantages of using ASCIIDOC, such as:   
- greater compatibility with GITenberg
- ability to use more semantic textual markup features

However, there are quite a few advantages to using markdown: 
- markdown is already considered "the _lingua franca_ of the Internet"  
- it's simpler, and doesn't require as much training, which would be great for adoption
- GitHub Pages supports markdown, but doesn't (yet) support ASCIIDOC

The last point is the killer feature here, in my opinion, since it enables us to use GitHub Pages out of the box, without involving Travis CI. 

Re: markdown flavor, it looks like the only one supported by Jekyll 3.0 at the moment is kramdown. So I'd vote for going with this format now as the canonical one, so we can start making jekyll-built editions using GitHub Pages. I'll close this issue for now, in the interest of moving this forward, but if anyone feels the need to revisit this, there is certainly plenty of room for discussion. 

In a minute, I'll open an issue for migrating @tfmorris's current ALTO->ASCIIDOC conversion script to markdown, which I don't think should be too painful.

**Comment by rufuspollock** [comment]
Great!
