### ISSUE TITLE
Move project to git-lit organization

### ISSUE THREAD

**Issue by tfmorris** [Git-Lit/git-lit#9]
It seems like this project and related issues would more appropriately be git-lit/git-lit.  Is there a reason to have it separate? (perhaps because there's a danger that there'll be a need to blow away the entire organization and all associated repos?)

**Comment by JonathanReeve** [comment]
Good idea. I'll try this: 
- [x] transfer the repo to github.com/Git-Lit
- [ ] fork the repo back here, to prevent link breakage 
- [ ] update the readme on the JonathanReeve/git-lit fork to say that it's been moved to Git-Lit

I did think that it'd be easier to wipe all the text repositories if there weren't any code repositories on Git-Lit, but if I keep a log of the created repositories, then I should just be able to delete them by name, anyway.

**Comment by JonathanReeve** [comment]
Sweet, looks like I didn't even need to fork it back to JonathanReeve/git-lit, since GitHub automatically forwards it here. Closing.
